// IPC Channel definitions — ทุก channel ต้องประกาศที่นี่เท่านั้น
// Push events (main → renderer): prefix event:*
// Request events (renderer → main): รูปแบบ category:action

export const enum IpcChannel {
  // Renderer → Main (invoke/handle)
  PROJECTS_LIST = 'projects:list',
  PROJECTS_ADD = 'projects:add',
  PROJECTS_REMOVE = 'projects:remove',
  PROJECTS_RENAME = 'projects:rename',
  PROJECTS_CONFIG_UPDATE = 'projects:config:update',
  PROJECTS_CONFIG_GET = 'projects:config:get',
  REPO_SCAN = 'repo:scan',
  REPO_SCAN_ALL = 'repo:scan:all',
  JIRA_TICKETS_FETCH = 'jira:tickets:fetch',
  JIRA_BOARD_FETCH = 'jira:board:fetch',
  JIRA_TEST = 'jira:test',
  JIRA_SETTINGS_SET = 'jira:settings:set',
  JIRA_SETTINGS_GET = 'jira:settings:get',
  JIRA_PROJECTS_SET = 'jira:projects:set',
  JIRA_PROJECTS_GET = 'jira:projects:get',
  TASK_IGNORE = 'task:ignore',
  TASK_UNIGNORE = 'task:unignore',
  TASK_TOGGLE = 'task:toggle',
  DANGERZONE_STATE = 'dangerzone:state',
  DRAFT_CREATE = 'draft:create',
  AI_START_MY_DAY = 'ai:start-my-day',
  KEYCHAIN_SET = 'keychain:set',
  KEYCHAIN_GET = 'keychain:get',
  KEYCHAIN_DELETE = 'keychain:delete',
  SCHEDULER_TRIGGER = 'scheduler:trigger',
  DIALOG_OPEN_FOLDER = 'dialog:open-folder',
  DIALOG_OPEN_FILE = 'dialog:open-file',
  NOTES_GET = 'notes:get',
  NOTES_SET = 'notes:set',
  AI_ASK = 'ai:ask',
  DEV_TOOLS_TOGGLE = 'devtools:toggle',
  SPRINT_STATUS_GET = 'sprint:status:get',
  JIRA_SPRINT_ACTIVE = 'jira:sprint:active',
  SHELL_OPEN_EXTERNAL = 'shell:open-external',
  AI_GAPCHECK = 'ai:gapcheck',
  CREDENTIALS_LIST = 'credentials:list',
  CREDENTIALS_UPSERT = 'credentials:upsert',
  CREDENTIALS_DELETE = 'credentials:delete',
  CREDENTIALS_GET_PASSWORD = 'credentials:get-password',
  CREDENTIALS_GET_TOKEN = 'credentials:get-token',
  CREDENTIALS_GET_SECRET = 'credentials:get-secret',

  // Main → Renderer (webContents.send) — push events
  SYNC_COMPLETED = 'event:sync:completed',
  DANGER_ZONE_TRIGGERED = 'event:dangerzone:triggered',
  STREAM_CHUNK = 'event:stream:chunk',
  STREAM_END = 'event:stream:end',
  STREAM_ERROR = 'event:stream:error',
}
